ALTER TABLE users ADD COLUMN IF NOT EXISTS role VARCHAR(50) NOT NULL DEFAULT 'User';

DROP TABLE IF EXISTS song_collaborators CASCADE;
DROP TABLE IF EXISTS songs CASCADE;
DROP TABLE IF EXISTS albums CASCADE;
DROP TABLE IF EXISTS artists CASCADE;

CREATE TABLE artists (
	id UUID PRIMARY KEY,
	user_id UUID UNIQUE REFERENCES users(id) ON DELETE RESTRICT,
	name VARCHAR(255) UNIQUE NOT NULL,
	bio TEXT,
	photo_url VARCHAR(255) NOT NULL DEFAULT 'http://minio:9000/bside-covers/default_artist_pp.png',
	status VARCHAR(50) NOT NULL DEFAULT 'Ready',
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE albums (
	id UUID PRIMARY KEY,
	artist_id UUID NOT NULL REFERENCES artists(id) ON DELETE CASCADE,
	title VARCHAR(255) NOT NULL,
	genre VARCHAR(100) NOT NULL,
	cover_url VARCHAR(255) NOT NULL,
	status VARCHAR(50) NOT NULL DEFAULT 'Ready',
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE songs (
	id UUID PRIMARY KEY,
	album_id UUID NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
	title VARCHAR(255) NOT NULL,
	duration_seconds INTEGER NOT NULL DEFAULT 0,
	audio_url VARCHAR(255) NOT NULL,
	ml_features JSONB,
	status VARCHAR(50) NOT NULL DEFAULT 'Ready',
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE song_collaborators (
	song_id UUID NOT NULL REFERENCES songs(id) ON DELETE CASCADE,
	artist_id UUID NOT NULL REFERENCES artists(id) ON DELETE CASCADE,
	role VARCHAR(50) NOT NULL DEFAULT 'Featured',
	PRIMARY KEY (song_id,artist_id)
);
